name: CI

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Type Check
        run: npm run typecheck
      - name: Lint
        run: npm run lint
