name: PR Checks

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Client Setup
        uses: ./.github/composite_actions/client-setup
      - name: Type Check
        run: pnpm run tsc

  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Client Setup
        uses: ./.github/composite_actions/client-setup
      - name: Lint
        run: pnpm run lint:check

  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Client Setup
        uses: ./.github/composite_actions/client-setup
      - name: Format Check
        run: pnpm run format:check

  app-build:
    name: App Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Client Setup
        uses: ./.github/composite_actions/client-setup
      - name: Build app
        run: pnpm run build
